# Generated by Django 4.0.5 on 2022-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('CP', 'Cargo Pants'), ('JK', 'Jacket')], default='S', max_length=2),
            preserve_default=False,
        ),
    ]
